name: 'Tech Marshmallow '
favicon: null
layout_spectrum: 0.647497744532302
typography_spectrum: 0.45590997277759016
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ADD7F6'
    - '#87BFFF'
    - '#3F8EFC'
    - '#2667FF'
    - '#3B28CC'
  brandStrength: 0.09299236279912293
  lightness: 0.6821379065513611
  saturation: 0.8097553956322372
  rhythmicContrast: 0.04179102461785078
purpose: []
